/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.de.htwg.conquest.ui.internal.ConquestActivator;

public class ConquestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConquestActivator.getInstance().getInjector("org.xtext.de.htwg.Conquest");
	}

}
