/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.de.htwg.ui.AbstractConquestUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ConquestUiModule extends AbstractConquestUiModule {
  public ConquestUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
