/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.de.htwg.ConquestRuntimeModule;
import org.xtext.de.htwg.ConquestStandaloneSetup;
import org.xtext.de.htwg.ide.ConquestIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ConquestIdeSetup extends ConquestStandaloneSetup {
  @Override
  public Injector createInjector() {
    ConquestRuntimeModule _conquestRuntimeModule = new ConquestRuntimeModule();
    ConquestIdeModule _conquestIdeModule = new ConquestIdeModule();
    return Guice.createInjector(Modules2.mixin(_conquestRuntimeModule, _conquestIdeModule));
  }
}
