/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide;

import org.xtext.de.htwg.ide.AbstractConquestIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ConquestIdeModule extends AbstractConquestIdeModule {
}
