/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ConquestStandaloneSetup extends ConquestStandaloneSetupGenerated {

	def static void doSetup() {
		new ConquestStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
