grammar org.xtext.de.htwg.Conquest with org.eclipse.xtext.common.Terminals

generate conquest "http://www.xtext.org/de/htwg/Conquest"

Conquest:
	'fieldsize' fieldsize = INT
	'players' playerList = PlayerList
	'colors' colorList = ColorList
;
	
PlayerList:
	'{' (players += Player)+ '}'
;
	
ColorList:
	'{' (colors += Color)+ '}'
;

Player:
	'name' name = STRING
	'cells' cells = INT
;

enum Color:
	RED | BLUE | GREEN | YELLOW | MAGENTA | CYAN | ORANGE | PINK
;
