/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg;

import org.xtext.de.htwg.ConquestStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConquestStandaloneSetup extends ConquestStandaloneSetupGenerated {
  public static void doSetup() {
    new ConquestStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
