/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.de.htwg.parser.antlr.internal.InternalConquestParser;
import org.xtext.de.htwg.services.ConquestGrammarAccess;

public class ConquestParser extends AbstractAntlrParser {

	@Inject
	private ConquestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConquestParser createParser(XtextTokenStream stream) {
		return new InternalConquestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public ConquestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConquestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
