/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.de.htwg.ide.contentassist.antlr.internal.InternalConquestParser;
import org.xtext.de.htwg.services.ConquestGrammarAccess;

public class ConquestParser extends AbstractContentAssistParser {

	@Inject
	private ConquestGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalConquestParser createParser() {
		InternalConquestParser result = new InternalConquestParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getGameAccess().getFieldAssignment(), "rule__Game__FieldAssignment");
					put(grammarAccess.getFieldAccess().getNameAssignment_1(), "rule__Field__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ConquestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConquestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
