/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.conquest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.conquest.Game#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.conquest.ConquestPackage#getGame()
 * @model
 * @generated
 */
public interface Game extends EObject
{
  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference.
   * @see #setField(Field)
   * @see org.xtext.de.htwg.conquest.ConquestPackage#getGame_Field()
   * @model containment="true"
   * @generated
   */
  Field getField();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.conquest.Game#getField <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' containment reference.
   * @see #getField()
   * @generated
   */
  void setField(Field value);

} // Game
